//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoDetallle
    {
        public int Id { get; set; }
        public string FacturaId { get; set; }
        public decimal MontoAplicado { get; set; }
        public decimal montoDeFacturaAlMomento { get; set; }
        public int Sincronizado { get; set; }
        public int IsDelete { get; set; }
        public int Compagni { get; set; }
    }
}
