//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int ID { get; set; }
        public string VendorID { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal MontoPagado { get; set; }
        public string MetodoDePago { get; set; }
        public string NumeroDeCheque { get; set; }
        public Nullable<System.DateTime> FechaDeCheque { get; set; }
        public bool habilitado { get; set; }
        public string ClienteId { get; set; }
        public bool Pendiente { get; set; }
        public int Sincronizado { get; set; }
        public int IsDelete { get; set; }
        public int Compagni { get; set; }
    }
}
