//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public int NumeroOrden { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public decimal totalAPagar { get; set; }
        public decimal Impuestos { get; set; }
        public string CreadoPor { get; set; }
        public int Sincronizado { get; set; }
        public int IsDelete { get; set; }
        public int Compagnia { get; set; }
    }
}
